version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs: 
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run: 
          name: Install Deps
          command: npm install
      - run:
          name: Build
          command: npm run build
  deploy-to-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Staging
          command: |
            echo "Deploying to Staging"
            curl $RENDER_STAGING_DEPLOYHOOK

workflows:
  run-tests-and-stage-workflow:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          command: npx run cypress --component
      - deploy-to-staging:
          requires: 
            - run-component-tests
          filters:
            branches:
              only: main
        